R-1102/MyRiyal

app/src/main/java/com/example/myriyal/MainActivity.kt, app/src/main/java/com/example/myriyal/screens/categories/data/repository/CategoryRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/repository/CategoryRepository.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/CategoryScreen.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/vmModels/CategoryViewModel.kt
Created a logic for adding a category and viewing a category
=> Create add category and view category

app/src/main/java/com/example/myriyal/MainActivity.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/useCases/CategoryUseCases.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/useCases/DeleteCategoryUseCase.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/useCases/GetAllCategoriesUseCase.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/useCases/InsertCategoryUseCase.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/useCases/SeedPredefinedCategoriesUseCase.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/useCases/SoftDeleteCategoryUseCase.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/useCases/UpdateCategoryUseCase.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/vmModels/CategoryViewModel.kt
I used the UseCase layer in the category  for the database
=> I used UseCase layer for the database

app/src/main/java/com/example/myriyal/navigation/AppNavGraph.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/component/GradientButton.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/BalanceScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/SignUpScreen.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/strings.xml
- Add Balance Screen after Signup Screen
- Arabic language
- Dark mood
=> Add Balance Screen

app/src/main/java/com/example/myriyal/MainActivity.kt, app/src/main/java/com/example/myriyal/MyRiyalApp.kt, app/src/main/java/com/example/myriyal/core/local/dao/RecordDao.kt, app/src/main/java/com/example/myriyal/navigation/testing/NavGraph.kt, app/src/main/java/com/example/myriyal/screens/mainScreen/MainScreen.kt, app/src/main/java/com/example/myriyal/screens/records/data/repository/RecordRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/records/domain/repository/RecordRepository.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/DeleteRecordUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/GetAllRecordsUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/GetRecordByIdUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/GetRecordsByCategoryUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/InsertRecordUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/RecordUseCases.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/UpdateRecordUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/vmModels/RecordViewModel.kt
Adding and viewing records are done
=> MR-27-Finish the add record and view record

app/src/main/java/com/example/myriyal/navigation/AppNavGraph.kt, app/src/main/java/com/example/myriyal/navigation/Routes.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/component/CustomCard.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/component/CustomTextField.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/ForgotPassword.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/LoginScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/NewPassword.kt, app/src/main/java/com/example/myriyal/ui/theme/Color.kt, app/src/main/java/com/example/myriyal/ui/theme/Theme.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/strings.xml
- Add Balance UI
- Add Forgot Password UI
- Update Signup & Login Screens
=> MR-49 Add Balance UI - Update Other Screens

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myriyal/MainActivity.kt, app/src/main/java/com/example/myriyal/MyApplication.kt, app/src/main/java/com/example/myriyal/MyRiyalApp.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/model/file, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/SignUpScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/SignUpVM.kt, app/src/main/java/com/example/myriyal/screens/categories/data/repository/CategoryRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/repository/CategoryRepository.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/vmModels/CategoryViewModel.kt, build.gradle.kts, gradle/libs.versions.toml
Push the DI implementation so it could work in all the other team members' project files.
The clean-up architecture is left to be done next (on sign-up - authentication).
=> MR-57- Set up Dependency injection implementation

app/google-services.json
I added Google service json file to fix the compile error
=> MR-66-Fix Compile Error-Add google services json file

app/src/main/java/com/example/myriyal/di/AppModule.kt
make the **AppModule** an object instead of an abstract class.
=> Sub task/mr 67 debug hilt dependency injection

app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/BalanceScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/ForgotPassword.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/LoginScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/NewPassword.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/SignUpScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/SplashScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/AddRecordScreen.kt, app/src/main/res/values/dimens.xml
Update Authentication Screens Dimensions
=> MR-65 Update Authentication Screens Dimensions

app/src/main/java/com/example/myriyal/MainActivity.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/AddCategory.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/vmModels/CategoryViewModel.kt
MR-68 - Cleaning the addCategory instead of using remember, we are using the viewModel
=> MR-68 - Cleaning the addCategory(remember) and using the viewModel

app/src/main/java/com/example/myriyal/AppNavigation.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/ViewRecordScreen.kt
Debugged some codes in Application
=> MR-72-Debug NavBar & ViewRecoreScreen UI

app/src/main/java/com/example/myriyal/MainActivity.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/data_sources/AuthDataSource.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/repositories_imp/AuthRepoImp.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/repository/AuthRepo.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/useCases/LogInUseCase.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/LoginScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/LogInVM.kt
Added the logic of login using FirebaseAuth, might be checked again later on.
=> MR-38- LogIn Logic

app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/AddCategory.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/ColorPicker.kt
I debug the wheel color in add category
=> MR-71 - I debug the color wheel in the add category

app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/navigation/ScreensSealedClasses.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/EditBalanceDialog.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/EditNameDialog.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/ViewProfileScreen.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
I've implemented the UI part of view profile
=> MR-78-Implementing the UI part view User profile

app/src/main/java/com/example/myriyal/screenComponent/CancelButton.kt, app/src/main/java/com/example/myriyal/screenComponent/CustomFloatingActionButton.kt, app/src/main/java/com/example/myriyal/screenComponent/FilterSelector.kt, app/src/main/java/com/example/myriyal/screenComponent/GradientButton.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/ColorPicker.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordItemCard.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/ViewRecordScreen.kt, app/src/main/java/com/example/myriyal/ui/theme/Color.kt, app/src/main/java/com/example/myriyal/ui/theme/Theme.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Enhance the UI & use the dimens.xml file 
<p align="center">
=> Sub task/mr 73 filtering records UI

app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/EditBalanceDialog.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/EditNameDialog.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/ViewProfileScreen.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/strings.xml
I've implemented the UI part of (Edit User Profile)
=> MR-81-Implementing the UI part of edit User profile

app/src/main/java/com/example/myriyal/di/RecordUseCaseModule.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordFormScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordItemCard.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/ViewRecordScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/vmModels/RecordViewModel.kt, app/src/main/java/com/example/myriyal/utils/provideRecordViewModel.kt
implying DI in the records files, debug the filter record, using the VMs instead, remember
=> MR-82 - implying DI in record's files Debug the filter record

app/src/main/java/com/example/myriyal/di/AuthModule.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/repositories_imp/AuthRepoImp.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/repository/AuthRepo.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/useCases/LogOutUseCase.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/LogOutVM.kt
**Implemented LogOut logic** in respect of clean architecture MVVM + DI
=> MR-84- LogOut Logic

app/src/main/java/com/example/myriyal/di/AuthModule.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/data_sources/AuthDataSource.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/repositories_imp/AuthRepoImp.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/repository/AuthRepo.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/useCases/ForgotPasswordUseCase.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/ForgotPassword.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/ForgotPasswordVM.kt
Implemented the logic to send a reset password request through email.
=> MR-85- Forget Password Logic

.idea/deploymentTargetSelector.xml, app/src/main/java/com/example/myriyal/core/local/dao/RecordDao.kt, app/src/main/java/com/example/myriyal/core/local/db/MyRiyalDB.kt, app/src/main/java/com/example/myriyal/core/local/entities/UserEntity.kt, app/src/main/java/com/example/myriyal/di/DatabaseModule.kt, app/src/main/java/com/example/myriyal/di/RecordUseCaseModule.kt, app/src/main/java/com/example/myriyal/di/UserModule.kt, app/src/main/java/com/example/myriyal/screens/Profile/data/repository/UserRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/Profile/domain/repository/UserRepository.kt, app/src/main/java/com/example/myriyal/screens/Profile/domain/useCases/CreateGuestUserUseCase.kt, app/src/main/java/com/example/myriyal/screens/Profile/domain/useCases/UserUseCases.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/EditBalanceDialog.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/EditNameDialog.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/ViewProfileScreen.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/vmModels/ProfileViewModel.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/ViewCategoryScreen.kt, app/src/main/java/com/example/myriyal/screens/records/data/repository/RecordRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/records/domain/repository/RecordRepository.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/GetTotalBalanceUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/RecordUseCases.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordItemCard.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/ViewRecordScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/vmModels/RecordViewModel.kt
MR-79 - I have Completed the user profile feature, now the balance can change based on transactions
=> Sub task/mr 79 user profile logic

app/build.gradle.kts, app/src/main/java/com/example/myriyal/di/AuthModule.kt, app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/SignUpScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/SignUpVM.kt, gradle/libs.versions.toml
Now the user **can not navigate to the next screen till the sign-up is successful.**
Also, **added a toast notification** to handle each field constraint to be interactive with the user's action.
=> Sub task/mr 74 show sign up status in UI

app/src/main/java/com/example/myriyal/MainActivity.kt, app/src/main/java/com/example/myriyal/navigation/AppNavigation.kt, app/src/main/java/com/example/myriyal/navigation/topBar/ProfileDropdownMenu.kt, app/src/main/java/com/example/myriyal/navigation/topBar/TopNavigationBar.kt, app/src/main/java/com/example/myriyal/screenComponent/CustomFloatingActionButton.kt, app/src/main/java/com/example/myriyal/screenComponent/GradientButton.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/ViewCategoryScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/ViewRecordScreen.kt, app/src/main/java/com/example/myriyal/ui/theme/Theme.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
- Implement the TopBar
- Dark Mode Icon 
- User Profile access through the top bar
- Log out through the top bar
=> MR-10 Implement the TopBar

app/src/main/java/com/example/myriyal/core/local/dao/RecordDao.kt, app/src/main/java/com/example/myriyal/di/RecordUseCaseModule.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/ViewProfileScreen.kt, app/src/main/java/com/example/myriyal/screens/records/data/repository/RecordRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/records/domain/repository/RecordRepository.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/RecordUseCases.kt, app/src/main/java/com/example/myriyal/screens/records/domain/useCases/SearchRecordsByNameUseCase.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordFormScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/ViewRecordScreen.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/vmModels/RecordViewModel.kt, app/src/main/res/values/dimens.xml
Now we can search the transitions by their names
=> Sub task/mr 58 searching record logic

app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/LoginScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/LogInVM.kt
Handle the logic of **only navigate when Log In is successful**
=> MR-75- Show LogIn status in UI

app/src/main/java/com/example/myriyal/home/HomeScreen.kt, app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/navigation/ScreensSealedClasses.kt, app/src/main/java/com/example/myriyal/navigation/bottomBar/NavItem.kt, app/src/main/java/com/example/myriyal/navigation/topBar/TopNavigationBar.kt, app/src/main/java/com/example/myriyal/screens/Profile/presentattion/screens/ViewProfileScreen.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/strings.xml
- Basic Cards for the home screen.
=> Sub task/mr 88 home screen basic UI

app/src/main/java/com/example/myriyal/navigation/AppNavigation.kt, app/src/main/java/com/example/myriyal/navigation/AppNavigationVM.kt, app/src/main/java/com/example/myriyal/navigation/NavGraph.kt
User can logout from Top Bar/Profile successfully.
=> MR-90- LogOut Implementation in the UI

app/src/main/java/com/example/myriyal/screens/categories/presentation/model/CategoryFilter.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/CategoryFilterDropdown.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/ViewCategoryScreen.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/vmModels/CategoryViewModel.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Added the logic of the category filter.
=> MR-25- Category Filter Logic Implementation

app/build.gradle.kts, app/src/main/java/com/example/myriyal/di/AppModule.kt, app/src/main/java/com/example/myriyal/di/EncryptedSharedPreferencesModule.kt, app/src/main/java/com/example/myriyal/home/HomeScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/repositories_imp/NotificationRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/repository/NotificationRepository.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/useCases/GetFcmTokenUseCase.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/useCases/LogOutUseCase.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/LogInVM.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/NotificationViewModel.kt, gradle/libs.versions.toml
Implemented EncryptedSharedPreferences and stored the token in it
=> Sub task/mr 101 shared preferences implement the shared preferences

app/src/main/java/com/example/myriyal/screens/categories/data/api/CategoryApiService.kt, app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/CategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/LocalCategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/RemoteCategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/repository/CategoryRepositoryImpl.kt
Only fixing the issue of the UI for not displaying the categories.
=> Debug-Showing the categories in the UI.

app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/RemoteCategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/repository/CategoryRepositoryImpl.kt
post predefined Categories to API
=> MR-105 post predefined Categories to API

app/src/main/java/com/example/myriyal/home/CustomCardHomeStatistic.kt, app/src/main/java/com/example/myriyal/home/HomeScreen.kt, app/src/main/java/com/example/myriyal/home/RecordItemCardSimple.kt, app/src/main/java/com/example/myriyal/home/ViewMoreComponent.kt, app/src/main/java/com/example/myriyal/screens/records/presentation/screens/RecordFormScreen.kt, app/src/main/java/com/example/myriyal/ui/theme/Color.kt, app/src/main/java/com/example/myriyal/ui/theme/Theme.kt, app/src/main/res/values/dimens.xml
- Add Balance and Records to Home Screen 
- update dark mood
=> MR-108 Add Balance and Records to Home Screen

app/src/main/java/com/example/myriyal/home/HomeScreen.kt, app/src/main/java/com/example/myriyal/home/RecordItemCardSimple.kt, app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/navigation/ScreensSealedClasses.kt, app/src/main/java/com/example/myriyal/navigation/bottomBar/NavItem.kt, app/src/main/java/com/example/myriyal/navigation/topBar/TopNavigationBar.kt, app/src/main/java/com/example/myriyal/screenComponent/CustomCardHomeStatistic.kt, app/src/main/java/com/example/myriyal/screens/graphsRepresentation/presentation/screens/ViewStatisticScreen.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
- Statistic Screen Basic Cards
=> MR-112 Statistic Screen Basic Cards

app/src/main/java/com/example/myriyal/di/AuthModule.kt, app/src/main/java/com/example/myriyal/navigation/AppNavigation.kt, app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/navigation/ScreensSealedClasses.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/data_sources/AuthDataSource.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/repositories_imp/AuthRepoImp.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/repository/AuthRepo.kt, app/src/main/java/com/example/myriyal/screens/authentication/domain/useCases/LogOutUseCase.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/SplashScreen.kt
When the user logs out, the shared reference will be cleaned, so the app will ask for user authentication (sign up/log in) in the next launch.
=> MR-110 debug log out logic

app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/RemoteCategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/repository/CategoryRepositoryImpl.kt
-  Fix Delete category in local
=> MR-116 Fix Delete category in local

app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/LoginScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/SignUpScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/LogInVM.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/SignUpVM.kt
=> MR-117 Review Signup Login logic

app/src/main/java/com/example/myriyal/core/db/MyRiyalDB.kt, app/src/main/java/com/example/myriyal/core/di/DatabaseModule.kt, app/src/main/java/com/example/myriyal/navigation/NavGraph.kt, app/src/main/java/com/example/myriyal/screens/authentication/data/repository/NotificationRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/screens/LoginScreen.kt, app/src/main/java/com/example/myriyal/screens/authentication/presentation/vmModels/NotificationViewModel.kt, app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/CategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/LocalCategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/dataSources/RemoteCategoryDataSource.kt, app/src/main/java/com/example/myriyal/screens/categories/data/local/CategoryDao.kt, app/src/main/java/com/example/myriyal/screens/categories/data/local/CategoryEntity.kt, app/src/main/java/com/example/myriyal/screens/categories/data/mapper/mappers.kt, app/src/main/java/com/example/myriyal/screens/categories/data/model/CategoryDto.kt, app/src/main/java/com/example/myriyal/screens/categories/data/remote/CategoryApiService.kt, app/src/main/java/com/example/myriyal/screens/categories/data/repository/CategoryRepositoryImpl.kt, app/src/main/java/com/example/myriyal/screens/categories/domian/repository/CategoryRepository.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/CategoryForm.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/CategoryItemCard.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/ViewCategoryScreen.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/vmModels/CategoryViewModel.kt, app/src/main/java/com/example/myriyal/screens/profile/presentattion/screens/ViewProfileScreen.kt
Fetch data from API and insert it in local DB
=> Sub task/mr 109 fetch the date from the api category

app/build.gradle.kts, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/CategoryForm.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/components/ColorPicker.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/vmModels/CategoryViewModel.kt, app/src/main/java/com/example/myriyal/screens/graphsRepresentation/presentation/screens/ExpenseIncomeLineChart.kt, app/src/main/java/com/example/myriyal/screens/graphsRepresentation/presentation/screens/ViewStatisticScreen.kt, app/src/main/res/values/dimens.xml, gradle/libs.versions.toml
added "ok" button to the color wheel dialog and a static UI chart
=> Sub task/mr 118 add ok button to color wheel dialog and a chart

app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/CategoryForm.kt, app/src/main/java/com/example/myriyal/screens/categories/presentation/screens/components/ColorPicker.kt, app/src/main/java/com/example/myriyal/screens/graphsRepresentation/presentation/screens/ViewStatisticScreen.kt, app/src/main/java/com/example/myriyal/screens/home/HomeScreen.kt, app/src/main/res/values/dimens.xml
- Home UI Modifications 
- Debug last merge
=> MR-122 Home UI Modifications / Debug last merge
